# Copyright 2018 Google Inc. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.
runtime: go111

handlers:
# Configure App Engine to serve any static assets.
- url: /views
  static_dir: views

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: edata-222505:us-central1:edatafarm
  # Replace username and password if you aren't using the root user.
  CLOUDSQL_USER: postgres
  CLOUDSQL_PASSWORD: ccF8mOFOF49ky59j
  CLOUDSQL_SOCKET_PREFIX: gcp
  # Switch GIN to "release" mode in production.
  GIN_MODE: release

beta_settings:
  cloud_sql_instances: edata-222505:us-central1:edatafarm